---
- hosts: all
  remote_user: ksala
  become: yes
  become_method: sudo

  tasks:
    - import_role:
        name: new-user

  vars:
    users: { "username": "amg", "sudo": false, "nosudopass": false }