---
- hosts: all
  remote_user: ksala
  become: yes
  become_method: sudo

  tasks:
    - include_vars: users.yml
      tags: always

    - name: Add | Del user
      include_role:
        name: new-user
      with_items: "{{ userlist }}"
      loop_control:
        loop_var: users
      tags: [never,useradd,userdel,prompt]

#      loop:
#        - username: amg
#          use_sudo: no
#        - username: amg2
#      loop_control:
#        loop_var: users