---
- import_tasks: useradd.yml
  tags: [useradd]

- import_tasks: userdel.yml
  tags: [userdel]

- import_tasks: visudo.yml
  tags: [nosudopass]

- import_tasks: prompt.yml
  tags: [prompt]

- include_vars: users.yml
