---
- include_vars: users.yml

- name: Create users with home directory
  user: 
    name: '{{ item.username }}' #testPass
    #password: $6$mysecretsalt$fW/zAIUL5i/w52EBBLAB4KjnR9YLyVhglW0XxECBTUTL6eYg3Eixq92rUXR680EyOoccOzQAR2.by8ITrniJm.
    shell: /bin/bash 
    createhome: yes
    state: present
  with_items: '{{users}}'

- name: Add user to wheel
  user: 
    name: '{{ item.username }}'
    shell: /bin/bash
    groups: wheel
    append: yes
  with_items: '{{users}}'
  tags: sudo

- name: ssh dir
  file:
    path: /home/{{ item.username }}/.ssh
    state: directory
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 0700
  with_items: '{{users}}'

- name: copy ssh keys
  copy:
    src: pub.key
    dest: /home/{{ item.username }}/.ssh/authorized_keys
    mode: 0700
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
  with_items: '{{users}}'
