---
- name: Create users with home directory
  user: 
    name: '{{ users.username }}' #testPass
    #password: $6$mysecretsalt$fW/zAIUL5i/w52EBBLAB4KjnR9YLyVhglW0XxECBTUTL6eYg3Eixq92rUXR680EyOoccOzQAR2.by8ITrniJm.
    shell: /bin/bash 
    createhome: yes
    state: present

- name: Add user to wheel
  user: 
    name: '{{ users.username }}'
    shell: /bin/bash
    groups: wheel
    append: yes
  when: "{{users.sudo|bool}} == True"

- name: add sudo no password
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  when: "{{users.nosudopass|bool}} == True"

- name: ssh dir
  file:
    path: /home/{{ item.username }}/.ssh
    state: directory
    owner: '{{ users.username }}'
    group: '{{ users.username }}'
    mode: 0700

- name: copy ssh keys
  copy:
    src: pub.key
    dest: /home/{{ item.username }}/.ssh/authorized_keys
    mode: 0700
    owner: '{{ users.username }}'
    group: '{{ users.username }}'
