---
- name: color ps1
  lineinfile:
    backup: yes
    state: present
    dest: "/root/.bashrc"
    line: export PS1='\[\e[1;31m\]\u\[\e[1;33m\]@\[\e[1;36m\]\h \[\e[1;33m\]\w \[\e[1;35m\]\$ \[\e[0m\]'
